/** Purpose: This Class is used to make a constant format.
*
* Created by: Shubh Shree Rathore
* 
* Created Date : 10-06-2019
* 
* Version : V.0 Created
* 
* revision logs:V1.0 -Shubh Shree Rathore - 10-06-2019
**/


public class FinalFormat {
    
    // Intialising the format of automobile sensor object 
    public   static final String AUTO_SENSOR = '00:11:CE:00';
    // Intialising the format of automobile presence sensor object
    public	 static final String AUTO_PRESENCE_SENSOR = '00:11:CE:D';
    // Intialising the format of automobile TDU object
    public   static final String AUTO_TDU = '00:11:CE:E';  
     
 
}